### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by matiasah** [danielga/gm_ffi#1]
Hello, your job here looks quite promising. But I'm not quite used to low-level compilers like MSVC, in fact, I did attempt to compile things like this before but it seems quite complex for regular Lua coders.
Is there by any chance that you could provide a distribution (dll) of gm_ffi?

**Comment by danielga** [comment]
Released Windows binaries [here](https://github.com/danielga/gm_ffi/releases/tag/downloadables).
