### ISSUE TITLE
Requiring

### ISSUE THREAD

**Issue by matiasah** [danielga/gm_ffi#2]
Hello again, we installed it on our server but we're now dealing with a new problem.
We expected that the right way to set it up was this:
`ffi = require("ffi")`

But then we printed the value of 'ffi' and we figured out that require("ffi") returns nil, so we're not sure about how we should correctly load the library.
- The installation was correct, it doesn't give any errors when you load the module.

**Comment by danielga** [comment]
Blame Garry for destroying compatibility with modules.
The correct way to do it in Garry's Mod is:

```
require("ffi")
ffi.new('void *', 0) == ffi.NULL -- true
```

So basically, the module creates a global table called ffi.

**Comment by matiasah** [comment]
I don't get it, Garry broke the module compatibility? I'm doing this (via gcompute)
`_G.require("ffi")`
`print(_G.ffi, "some additional message")`
But it prints this
`nil    some additional message`
The code is being run server-side.

**Comment by danielga** [comment]
No errors?

**Comment by matiasah** [comment]
There wasn't any error.

**Comment by matiasah** [comment]
I did another thing to make sure that the function environment that the code is running at doesn't affect the module. I used this command via rcon
`lua_run require("ffi") print(ffi)`
And the console outputs
`> require("ffi") print(ffi)...`
`nil`

**Comment by danielga** [comment]
```
lua_run require("ffi")
> require("ffi")...
lua_run print(ffi)
> print(ffi)...
table: 0x00c82040
```

Works fine for me on both Windows and Linux.

**Comment by matiasah** [comment]
Indeed, it now works. I can't guess why it didn't do that before.

**Comment by danielga** [comment]
Did you restart the server after having done `ffi = require("ffi")` ?
Because what that did was set the global ffi table to nil and since require doesn't actually load the module multiple times, it was gone the moment that was executed.
By restarting, the module is unloaded and so can be required once more.

**Comment by matiasah** [comment]
Ah that makes sense. But still, the code was running in a custom environment so that shouldn't have happened.
