### ISSUE TITLE
Is there a limitation to what can be used with this for FFI?

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gm_ffi#8]
For example if I were to use this would I be able to access source engine functions or classes that are compiled into srcds or would I be limited to just standard library stuff?

**Comment by danielga** [comment]
You can access anything you want, as long as you know how to find it.

**Comment by VaasKahnGrim** [comment]
Thank you, was digging around for a few days trying to figure out if it was limited to just std stuff or required a compiler to also be on the same machine. Saved me a massive headache in figuring out what I might be limited to

**Comment by pkmnmstr98** [comment]
@VaasKahnGrim so what is it limited to :) ?
