### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by unknown-gd** [danielga/gm_ffi#9]
![image](https://user-images.githubusercontent.com/44779902/206805971-26ccb68e-1776-40bc-9b3e-803fa8dd76b3.png)

**Comment by danielga** [comment]
I pushed an update that should hopefully fix that.

**Comment by unknown-gd** [comment]
![image](https://user-images.githubusercontent.com/44779902/207286168-7f9d3ae2-60ec-429e-bfa6-edc473c366f4.png)
👌
